package com.mobs;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

public class MobsList {
    private static final AtomicReference<List<Mob>> mobCache = new AtomicReference<>();
    
    public static List<Mob> getAllMobs() {
        List<Mob> mobs = mobCache.get();
        if (mobs == null) {
            synchronized (MobsList.class) {
                mobs = mobCache.get();
                if (mobs == null) {
                    mobs = initializeMobs();
                    mobCache.set(mobs);
                }
            }
        }
        return mobs;
    }
    
    private static List<Mob> initializeMobs() {
        return Arrays.asList(
            new Mob("Allay", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/45/Allay_JE2.gif/revision/latest?cb=20230325131818", 
                "Passive", 
                "Overworld", 
                "Pillager Outpost | Woodland Mansion", 
                20, 
                "♥ × 10", 
                0, 
                "♥ × 0", 
                0.6, 
                "Height: 0.6 Blocks | Width: 0.6 Blocks", 
                "The allay is a flying passive mob that collects and delivers items for any player that gives it something or any note block it hears recently playing."), 
            new Mob("Armadillo", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/9f/Armadillo.png/revision/latest?cb=20240729213938", 
                "Passive", 
                "Overworld", 
                "Savanna | Savanna Plateau | Windswept Savanna | Badlands | Eroded Badlands | Wooded Badlands", 
                6, 
                "♥♥♥", 
                0, 
                "♥ × 0", 
                0.7, 
                "Height: 0.65 blocks | Width: 0.7 blocks", 
                "Armadillo is a mob that spawns in warm biomes. Spider eyes, brushes, and lead can be used on the armadillo to breed, brush, or lead it respectively. When a player is sprinting, mounting, or causes harm to an armadillo, or when an undead hostile mob is nearby, it rolls up into a cube-like shape to protect itself from harm."),
            new Mob("Axolotl", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/99/Lucy_Axolotl_JE2.png/revision/latest/scale-to-width-down/1000?cb=20240729213943", 
                "Passive", 
                "Overworld", 
                "Lush Caves", 
                14, 
                "♥ × 7", 
                0, 
                "(2 ♥ Inflicted on mobs)", 
                0.75, 
                "Height: 0.42 Blocks | Width: 0.75 Blocks", 
                "An axolotl is a passive bucketable aquatic mob found in lush caves. Axolotls attack fish, squid, drowned, and guardians; this makes axolotls useful for assisting with aquatic combat. Axolotls grant players Regeneration."),
            new Mob("Bat", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c2/NewBat.gif/revision/latest?cb=20240716233759", 
                "Passive", 
                "Overworld", 
                "Below layer 63 Light level of 3 or less in neighboring blocks", 
                6, 
                "♥♥♥", 
                0, 
                "♥ × 0", 
                0.9, 
                "Height: 0.9 Blocks | Width: 0.5 Blocks", 
                "A bat is a flying ambient passive mob that spawns in dark areas underground in caves."),
            new Mob("Bee", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1e/Bee_Flying_BE.gif/revision/latest/scale-to-width-down/1000?cb=20230414023046", 
                "Neutral", 
                "Overworld", 
                "Naturally generated Bee Nests", 
                10, 
                "♥♥♥♥♥", 
                2, 
                "♥ (Poison 7 ♥♥♥♥)", 
                0.55, 
                "Height: 0.5 Blocks | Width: 0.55 Blocks", 
                "Bees are flying neutral mobs that live in bee nests and beehives. Bees pollinate flowers and, when they do, add honey to their home when they return to it. When full, bee nests or beehives can be harvested with shears for honeycombs or glass bottles for honey bottles. If provoked by being attacked or breaking or harvesting their hive or nest without the correct precautions, bees suicidally attack in a swarm."),
            new Mob("Blaze", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5a/Blaze.gif/revision/latest?cb=20230214143150", 
                "Hostile", 
                "The Nether", 
                "Nether Fortress", 
                20, 
                "♥ × 10", 
                6, 
                "♥♥♥ (Fireball 5 ♥♥♥)", 
                1.8, 
                "Height: 1.8 Blocks | Width: 0.5 Blocks", 
                "A blaze is a hostile mob that spawns in nether fortresses and is the only source of blaze rods. Blazes attack at range by firing a trio of fireballs or can attack the player that gets too close to them with their spinning rods."),
            new Mob("Breeze", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/98/Breeze.png/revision/latest?cb=20240801215038", 
                "Hostile", 
                "Overworld", 
                "Trial Chambers", 
                30, 
                "♥ × 15", 
                1, 
                "♥", 
                1.77, 
                "Height: 1.77 Blocks | Width: 0.6 Blocks", 
                "A breeze is a floating hostile mob that is similar to the blaze that spawns in trial chambers. It attacks at range by firing wind charges. They drop breeze rods, which can be crafted into wind charges and the maces."),
            new Mob("Camel", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/09/Camel.png/revision/latest?cb=20240729213957", 
                "Passive", 
                "Overworld", 
                "Desert Village | Desert", 
                32, 
                "♥ × 16", 
                0, 
                "♥ × 0", 
                2.375, 
                "Height: 2.375 Blocks | Width: 1.7 Blocks", 
                "A camel is a passive mob found in deserts and desert villages and that can be saddled and ridden by up to two players at once. A camel is tall enough that its riders cannot be reached from the ground by a few melee-attacking harmful mobs, who do not attack the camel."),
            new Mob("Cat", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/b/b0/Calico_Cat.png/revision/latest?cb=20181102140807", 
                "Passive", 
                "Overworld", 
                "Villages | Swamp huts (only black cats)", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "(3 ♥♥ Inflicted on mobs)", 
                0.56, 
                "Height: 0.56 Blocks | Width: 0.48 Blocks", 
                "A cat is a passive mob found in villages and swamp huts. They can be tamed and used to repel creepers and phantoms."), 
            new Mob("Cave Spider", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/17/Cave_Spider_JE2_BE2.png/revision/latest/scale-to-width-down/1000?cb=20240729214008", 
                "Hostile (if light level 7 and below and if jockey ridden by skeletons, strays and wither skeletons). Neutral (if light level 8 and above)", 
                "Overworld", 
                "Mineshafts", 
                12, 
                "♥ × 6", 
                2, 
                "♥ (Poison 6 ♥♥♥)", 
                0.7, 
                "Height: 0.5 Blocks | Width: 0.7 Blocks", 
                "Cave spiders are small variants of the spider that inflict Poison with their attacks. They are exclusively spawned by monster spawners found in mineshafts."), 
            new Mob("Charged Creeper", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/eb/Charged_Creeper_Animated.gif/revision/latest?cb=20210604085020", 
                "Hostile", 
                "Overworld", 
                "Light level of 0", 
                20, 
                "♥ × 10", 
                85, 
                "♥ × 42.5", 
                1.8, 
                "Height: 1.8 Blocks | Width: 0.6 Blocks", 
                "When struck by lightning, a creeper becomes a charged creeper, which amplifies its explosion power and enables mob heads to be obtained from piglins, zombies, skeletons, and other creepers it kills."), 
            new Mob("Chicken", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2c/Chicken_JE2_BE2.png/revision/latest?cb=20240729214013", 
                "Passive", 
                "Overworld", 
                "Solid surfaced blocks with a minimum of two block spaces above them. A 1⁄8 chance from a thrown egg", 
                4, 
                "♥♥", 
                0, 
                "♥ × 0", 
                0.8, 
                "Height: 0.8 Blocks | Width: 0.6 Blocks", 
                "The chicken is a passive mob found in grass biomes and the main source of raw chicken, feathers, and eggs. A chicken, like most animals, can be attached to a lead."),
            new Mob("Chicken Jockey", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d3/Chicken_Jockey.png/revision/latest?cb=20250409082551", 
                "Hostile", 
                "Overworld", 
                "Randomly spawns instead of a baby zombie, baby husk, baby drowned or baby zombified piglin. " +
                                        "Chicken Jockey: " +
                                        "Light level of 0. " +
                                        "Chicken Husk Jockey: " +
                                        "Desert, Desert Hills, Desert Lakes. " +
                                        "Chicken Zombified Piglin Jockey: " +
                                        "Any 2 block high space in any light level in the Nether.", 
                20, 
                "♥ × 10 (Chicken ♥♥)", 
                3, 
                "♥♥", 
                1.3, 
                "Height: 1.3 Blocks | Width: 0.6 Blocks", 
                "Chicken jockeys[1] are the rare appearance of a baby zombie, baby zombified piglin, baby zombie villager, baby husk, or baby drowned riding a chicken."), 
            new Mob("Cod", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/66/Cod.gif/revision/latest?cb=20240729214018", 
                "Passive", 
                "Overworld", 
                "Cold Ocean | Deep Cold Ocean | Lukewarm Ocean | Deep Lukewarm Ocean | Ocean | Deep Ocean", 
                3, 
                "♥♥", 
                0, 
                "♥ × 0", 
                0.6, 
                "Height: 0.3 Blocks | Width: 0.6 Blocks", 
                "Cod are common bucketable aquatic passive mobs found in oceans, and a source of raw cod."), 
            new Mob("Cow", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5e/Cow_JE5_BE2.png/revision/latest?cb=20240729214026", 
                "Passive", 
                "Overworld", 
                "Grass blocks with at least two blocks of space above them. After shearing a mooshroom.", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                1.3, 
                "Height: 1.3 Blocks | Width: 0.9 Blocks", 
                "A cow is a passive mob and a source of leather, beef and milk. There are three different variants that spawn depending on the biome that the Cow spawns in."), 
            new Mob("Creaking", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c3/Creaking_Minecraft_JE_BE.png/revision/latest?cb=20241204074442", 
                "Hostile", 
                "Overworld", 
                "By an activated creaking heart at night or during thunderstorms.", 
                1, 
                "♥ (Immune to damage)", 
                3, 
                "♥♥", 
                2.5, 
                "Height: 2.5 Blocks | Width: 1 Block", 
                "The creaking is a hostile mob that generates in the pale garden from a creaking heart. A creaking cannot take any form of damage and is immune to knockback, but when hit by a player or pet, a trail of orange particles will appear between the creaking and its heart, and 2-3 resin clumps will be exuded on the sides of pale oak logs near the creaking heart. Once its creaking heart is destroyed, a creaking will twitch and then disintegrate."), 
            new Mob("Creeper", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Creeper_JE2_BE1.png/revision/latest?cb=20191229172043", 
                "Hostile", 
                "Overworld", 
                "Light level of 0", 
                20, 
                "♥ × 10", 
                43, 
                "♥ × 21.5", 
                1.8, 
                "Height: 1.8 Blocks | Width: 0.6 Blocks", 
                "A creeper is a common hostile mob that silently approaches players and then explodes, which can destroy blocks and kill unarmored players on any difficulty (except for peaceful)."), 
            new Mob("Dolphin", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/70/Dolphin.gif/revision/latest?cb=20240729214031", 
                "Neutral", 
                "Overworld", 
                "Lukewarm Ocean | Deep Lukewarm Ocean | Ocean | Deep Ocean | Warm Ocean", 
                10, 
                "♥♥♥♥♥", 
                3, 
                "♥♥", 
                0.9, 
                "Height: 0.6 Blocks | Width: 0.9 Blocks", 
                "Dolphins are neutral mobs that live in non-frozen oceans, which grant a speed boost to players that swim near them."), 
            new Mob("Donkey", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/95/Donkey.png/revision/latest?cb=20240728033758", 
                "Passive", 
                "Overworld", 
                "Meadow | Plains | Sunflower Plains | Savanna | Savanna Plateau | Windswept Savanna", 
                30, 
                "♥ × 15", 
                0, 
                "♥ × 0", 
                1.6, 
                "Height: 1.6 Blocks | Width: 1.4 Blocks", 
                "Donkeys are variants of horses that, when tamed, can be ridden and equipped with chests."), 
            new Mob("Drowned", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/33/Drowned_with_Trident.png/revision/latest?cb=20220420015955", 
                "Hostile (during nighttime and to players touching water). Passive (to players not touching water during daytime). Neutral (if a player does not touch water during daytime, AND the drowned is equipped with a Trident)", 
                "Overworld", 
                "When a zombie drowns | River | Frozen River | Cold Ocean | Deep Cold Ocean | Frozen Ocean | Deep Frozen Ocean | Lukewarm Ocean | Deep Lukewarm Ocean | Ocean | Deep Ocean | Warm Ocean | Dripstone Caves", 
                20, 
                "♥ × 10", 
                3, 
                "♥♥ (Trident 11 ♥ × 5.5)", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "Drowned are common underwater zombie variants that spawn in oceans, rivers and dripstone caves, or when zombies drown. They usually attack through melee attacks, but may also come armed with tridents that they throw. They are the only source of tridents, and the only renewable source of copper."), 
            new Mob("Elder Guardian", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/75/Elder_Guardian.gif/revision/latest?cb=20190925152022", 
                "Hostile", 
                "Overworld", 
                "Ocean Monument", 
                80, 
                "♥ × 40", 
                8, 
                "♥♥♥♥ (Spikes 2 ♥)", 
                1.9975, 
                "Height: 1.9975 Blocks | Width: 1.9975 Blocks", 
                "An elder guardian is a stronger and larger variant of the guardian, and the largest aquatic mob. It attacks the same way as a normal guardian, but also applies Mining Fatigue to players in a large radius around itself. They are only found in ocean monuments; three of them generate in each one."), 
            new Mob("Ender Dragon", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0a/Ender_Dragon.gif/revision/latest?cb=20210107043116", 
                "Hostile", 
                "The End", 
                "The End", 
                200, 
                "♥ × 100", 
                15, 
                "♥ × 7.5 (Breath ♥ × 4.5)", 
                16.0, 
                "Height: 8.0 Blocks | Width: 16.0 Blocks", 
                "The ender dragon is a giant flying hostile boss mob found when first entering the End. She is the largest naturally spawning mob in the game. She guards access to the end gateways that provide entry to the outer end islands in addition to the exit portal that allows return to the Overworld as well as access to the end credits of Minecraft. Because of this, she is known by most Minecraft fans as the 'final boss' of the game. Her attacks involve charging at the player and her unique dragon acid attacks."),
            new Mob("Enderman", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/39/Enderman_Screaming.gif/revision/latest?cb=20200413141725", 
                "Neutral", 
                "The End", 
                "Overworld and The End Light level of 0 | The Nether: Light level 7 or less | Nether Wastes | Soul Sand Valley | Warped Forest", 
                40, 
                "♥ × 20", 
                7, 
                "♥♥♥♥", 
                3.25, 
                "Height: 3.25 Blocks | Width: 0.6 Blocks", 
                "The Enderman is a tall neutral mob found in all three dimensions. Endermen normally ignore players and lazily amble about, but they will swiftly walk to attack those that damage it or look directly at its face. Endermen teleport to avoid water (which harms them), projectiles and some other damage sources, and they occasionally pick up certain blocks. They will also teleport more rapidly in sunlight."), 
            new Mob("Endermite", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/6/6e/Endermite.gif/revision/latest?cb=20200126021254", 
                "Hostile", 
                "The End", 
                "5% chance when an ender pearl lands", 
                8, 
                "♥♥♥♥", 
                2, 
                "♥", 
                0.4, 
                "Height: 0.3 Blocks | Width: 0.4 Blocks", 
                "An endermite is the smallest hostile mob. An endermite may spawn when a player throws an ender pearl. They attack by biting the player. Endermen are hostile toward endermites."), 
            new Mob("Evoker", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Evoker_JE2.png/revision/latest?cb=20220613062102", 
                "Hostile", 
                "Overworld", 
                "Woodland Mansions | Raids", 
                24, 
                "♥ × 12", 
                6, 
                "♥♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "An evoker is a spell-casting illager found in woodland mansions and raids, and the only source of the totem of undying. It uses two spells to attack; one that summons armor-piercing fangs and one that summons vexes."), 
            new Mob("Fox", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/73/Fox.png/revision/latest?cb=20240729214702", 
                "Passive (Wild or trusting player). Neutral (Trusting different player)", 
                "Overworld", 
                "Grove | Snowy Taiga | Old Growth Pine Taiga | Old Growth Spruce Taiga | Taiga", 
                20, 
                "♥ × 10", 
                2, 
                "♥", 
                0.7, 
                "Height: 0.7 Blocks | Width: 0.6 Blocks", 
                "A fox is a neutral mob that spawns in taigas, old growth taigas, snowy taigas and mountain groves. They are able to carry a single item in their mouth, but prefer food over other items."), 
            new Mob("Frog", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ce/Temperate_Frog_JE1_BE1.gif/revision/latest?cb=20240729215004", 
                "Passive", 
                "Overworld", 
                "Swamp | Mangrove Swamp", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                0.5, 
                "Height: 0.5 Blocks | Width: 0.5 Blocks", 
                "A frog is a passive mob found in swamps. Frogs eat small slimes and magma cubes. A frog can produce one of three kinds of froglights from eating magma cubes, depending on the type of frog."),            
            new Mob("Ghast", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d5/Ghast_JE2_BE2.gif/revision/latest?cb=20201108222940", 
                "Hostile", 
                "The Nether", 
                "Nether Wastes | Soul Sand Valley | Basalt Deltas", 
                10, 
                "♥♥♥♥♥", 
                17, 
                "♥ × 8.5", 
                4.0, 
                "Height: 4.0 Blocks | Width: 4.0 Blocks", 
                "Ghasts are large white floating ghost-like hostile mobs that live in the Nether and shoot explosive fireballs at the player."),
            new Mob("Glow Squid", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c3/Glow_Squid_JE1.gif/revision/latest?cb=20240729214706", 
                "Passive", 
                "Overworld", 
                "Anywhere where there is water underground, in schools of 2 to 4.", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                0.95, 
                "Height: 0.95 Blocks | Width: 0.95 Blocks", 
                "The glow squid is a variant of squid found in dark underwater areas, typically in ocean depths, ravines and underground lakes. It has an aqua luminescent texture. The mob originates from Minecraft Earth."),
            new Mob("Goat", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/f8/Goat_JE1_BE1.png/revision/latest?cb=20240729214711", 
                "Neutral", 
                "Overworld", 
                "Frozen Peaks | Jagged Peaks | Snowy Slopes", 
                10, 
                "♥♥♥♥♥", 
                2, 
                "♥", 
                1.3, 
                "Height: 1.3 Blocks | Width: 0.9 Blocks", 
                "A goat is a neutral mob found in certain mountainous biomes. Goats can jump especially high, and ram mobs. They are a source of goat horns and milk."), 
            new Mob("Guardian", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/94/Guardian.gif/revision/latest?cb=20190925152101", 
                "Hostile", 
                "Overworld", 
                "Ocean Monument", 
                30, 
                "♥ × 15", 
                6, 
                "♥♥♥ (Spikes 2 ♥)", 
                0.85, 
                "Height: 0.85 Blocks | Width: 0.85 Blocks", 
                "Guardians are pufferfish-like hostile mobs that spawn in and around ocean monuments. They attack with a slow-charging laser beam, and inflict retaliatory damage when damaged by a melee attack."), 
            new Mob("Hoglin", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/41/Hoglin_JE3.png/revision/latest?cb=20240729214720", 
                "Hostile", 
                "The Nether", 
                "Crimson Forest | Bastion remnant", 
                40, 
                "♥ × 20", 
                8, 
                "♥♥♥♥", 
                1.4, 
                "Height: 1.4 Blocks | Width: 1.4 Blocks", 
                "A hoglin is a breedable hostile mob found in the Nether, and a source of porkchops and leather. A hoglin attacks by thrusting its tusks upward, which can also launch its target a short distance into the air. Hoglins are repelled by warped fungi that is placed in the world as well as active nether portals and respawn anchors."), 
            new Mob("Hoglin Jockey", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Baby_Piglin_Riding_a_Baby_Hoglin.png/revision/latest?cb=20220531151123", 
                "Hostile", 
                "The Nether", 
                "Baby piglins run near and ride baby hoglins.", 
                56, 
                "♥ × 28", 
                1, 
                "♥", 
                1.15, 
                "Height: 1.15 Blocks | Width: 0.7 Blocks", 
                "Hoglin jockeys are the rare appearance of a baby piglin riding a baby hoglin. Baby piglins are passive and play with baby hoglins, running around and riding upon them. Up to 3 baby piglins may stack on top of each other while riding a baby hoglin."),            
            new Mob("Horse", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/86/White_Horse.png/revision/latest?cb=20240729214716", 
                "Passive", 
                "Overworld", 
                "Plains | Sunflower Plains | Savanna | Savanna Plateau | Windswept Savanna | Villages", 
                30, 
                "♥ × 15", 
                0, 
                "♥ × 0", 
                1.6, 
                "Height: 1.6 Blocks | Width: 1.4 Blocks", 
                "Horses are passive mobs that can be ridden when tamed and saddled."),
            new Mob("Husk", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e4/Husk_JE2_BE2.png/revision/latest?cb=20190510101810", 
                "Hostile", 
                "Overworld", 
                "Desert", 
                20, 
                "♥ × 10", 
                3, 
                "♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A husk is a variant of a zombie that spawns in deserts. They function similar to zombies, except they do not burn in sunlight and inflict Hunger with their unarmed attacks."), 
            new Mob("Iron Golem", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/02/Iron_Golem_JE2_BE2.png/revision/latest?cb=20190605101959", 
                "Neutral (naturally spawning, or summoned by commands). Passive (player-built, or in Peaceful difficulty)", 
                "Overworld", 
                "Near a pillager outpost | In Villages | When built by the player", 
                100, 
                "♥ × 50", 
                20, 
                "♥ × 10", 
                2.9, 
                "Height: 2.9 Blocks | Width: 1.4 Blocks", 
                "An iron golem is a buildable neutral mob that looks like a robot and attacks monsters with its arms, knocking them into the air. Iron golems created by villagers or spawned in villages patrol their village, and may attack players that attack it or have a low popularity or reputation with their village."), 
            new Mob("Llama", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/4a/Creamy_Llama.png/revision/latest?cb=20240729214726", 
                "Neutral", 
                "Overworld", 
                "Windswept Hills | Windswept Forest | Windswept Gravelly Hills | Savanna Plateau | Savanna | Windswept Savanna", 
                30, 
                "♥ × 15", 
                1, 
                "♥", 
                1.87, 
                "Height: 1.87 Blocks | Width: 0.9 Blocks", 
                "A llama is a tamable neutral mob used to transport large shipments of items using caravans.A trader llama is a special variant that follows wandering traders."), 
            new Mob("Magma Cube", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ed/Magma_Cube.png/revision/latest?cb=20190805151823", 
                "Hostile", 
                "The Nether", 
                "Nether Wastes | Basalt Deltas | Nether Fortress | Bastion Remnant", 
                20, 
                "♥ × 10", 
                4, 
                "♥♥", 
                2.08, 
                "Height: 2.08 Blocks | Width: 2.08 Blocks", 
                "A magma cube is a hostile mob found in the Nether. A magma cube behaves similarly to a slime, but is fireproof, jumps higher and less often, and deals more damage."), 
            new Mob("Mooshroom", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1c/Red_Mooshroom_JE4.png/revision/latest?cb=20240729214731", 
                "Passive", 
                "Overworld", 
                "Mushroom Fields", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                1.3, 
                "Height: 1.3 Blocks | Width: 0.9 Blocks", 
                "Mooshrooms are mushroom-covered variants of cows exclusive to the rare mushroom fields biome. Although they look similar to cows, they are not cows. A red mooshroom transforms into a brown mooshroom (and vice versa) when it is struck by lightning. Brown mooshrooms never spawn naturally. A mooshroom can be milked by using a bucket on it, yielding a milk bucket. Mooshrooms can also be milked using bowls to get mushroom stew."), 
            new Mob("Mule", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e7/Mule.png/revision/latest?cb=20240729214737", 
                "Passive", 
                "Overworld", 
                "When a horse and donkey breed", 
                30, 
                "♥ × 15", 
                0, 
                "♥ × 0", 
                1.6, 
                "Height: 1.6 Blocks | Width: 1.4 Blocks", 
                "Mules are infertile offspring of horses and donkeys that, when tamed, can be ridden and equipped with chests."), 
            new Mob("Ocelot", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/0/0d/Ocelot.png/revision/latest?cb=20240729214742", 
                "Passive", 
                "Overworld", 
                "Jungle | Bamboo Jungle | Sparse Jungle | Meadow", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "(3 ♥♥ Inflicted on mobs)", 
                0.7, 
                "Height: 0.7 Blocks | Width: 0.6 Blocks", 
                "An ocelot is a passive mob that may be found in jungles. Creepers stay six blocks away from an ocelot. A creeper within this range that has begun its detonation does not flee unless the player leaves its blast radius. Phantoms stay 16 blocks away from an ocelot."), 
            new Mob("Panda", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d9/Panda_Rolling.gif/revision/latest?cb=20200514023508", 
                "Neutral", 
                "Overworld", 
                "Jungle | Bamboo Jungle | Sparse Jungle", 
                20, 
                "♥ × 10", 
                6, 
                "♥♥♥", 
                1.3, 
                "Height: 1.25 Blocks | Width: 1.3 Blocks", 
                "A panda is a rare neutral mob that resides in jungles. Certain aspects of a panda's behavior and appearance vary depending on its personality. Baby pandas have a 1⁄6000 chance (0.01666%) of sneezing every tick. Weak baby pandas are more likely to sneeze with a 1⁄500 (0.2%) chance every tick. Sneezing makes all adult pandas within 10 blocks jump and rarely drops a slimeball. Baby pandas also occasionally roll over and jump around."), 
            new Mob("Parrot", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/de/Red_Parrot.png/revision/latest?cb=20240729214753", 
                "Passive", 
                "Overworld", 
                "Jungle | Bamboo Jungle | Sparse Jungle", 
                6, 
                "♥♥♥", 
                0, 
                "♥ × 0", 
                1.0, 
                "Height: 1 Block | Width: 0.5 Blocks", 
                "A parrot is a tameable passive mob that spawns in jungle biomes. Parrots can imitate sounds of nearby monsters and can also perch on the player's shoulders."), 
            new Mob("Phantom", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/39/Phantom_JE2.gif/revision/latest?cb=20180706142237", 
                "Hostile", 
                "Overworld", 
                "At nighttime or during thunderstorms, when player has not entered a bed for at least 3 ingame days.", 
                20, 
                "♥ × 10", 
                6, 
                "♥♥♥", 
                0.9, 
                "Height: 0.5 Blocks | Width: 0.9 Blocks", 
                "Phantoms are flying undead hostile mobs that spawn in the night sky when the player has not laid in a bed or died for three or more in-game days. They attack by diving at the player from the sky to bite them. Usually, they appear in trios."), 
            new Mob("Pig", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1a/Pig_JE3_BE2.png/revision/latest?cb=20240729065554", 
                "Passive", 
                "Overworld", 
                "Grass with at least two block space above.", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                0.9, 
                "Height: 0.9 Blocks | Width: 0.9 Blocks", 
                "A pig is a passive mob found commonly in most grass biomes, though they also can also spawn in the Taiga biomes, the Badlands, Savanna, and Jungle biomes with seperate variants. Pigs are a source of porkchops and can be equipped with a saddle to be driven."), 
            new Mob("Piglin", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ea/Piglin_BE.png/revision/latest?cb=20200730232135", 
                "Neutral", 
                "The Nether", 
                "Nether Wastes | Crimson Forest | Bastion remnant", 
                16, 
                "♥ × 8", 
                9, 
                "♥ × 4.5 (Crossbow 4 ♥♥)", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A piglin is a neutral mob found in the Nether. It is hostile to players unless they wear at least one piece of golden armor. It can be given gold ingots to barter for various items. It wields either a golden sword or a crossbow, and uses either melee or ranged attacks, respectively. Baby piglins do not grow up, never hold weapons or attack, and take gold without giving anything in return."), 
            new Mob("Piglin Brute", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/5b/Piglin_Brute.png/revision/latest?cb=20230723003220", 
                "Hostile", 
                "The Nether", 
                "Bastion remnant", 
                50, 
                "♥ × 25", 
                10, 
                "♥♥♥♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A piglin brute is a hostile and stronger variant of piglins that appears in all types of bastion remnants. Unlike regular piglins, they do not barter or retreat, and they cannot be distracted with gold. Instead, they always charge at the player on sight with their golden axes."), 
            new Mob("Pillager", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/55/Pillager_JE3.png/revision/latest?cb=20220714205247", 
                "Hostile", 
                "Overworld", 
                "Patrols | Pillager outposts | Raids", 
                24, 
                "♥ × 12", 
                3, 
                "♥♥ (Crossbow 4 ♥♥)", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "Pillagers are hostile mobs armed with crossbows found in wandering patrols, in pillager outposts, or as participants in raids. They attack by firing arrows at the player."), 
            new Mob("Player", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8f/Steve_%28classic%29_JE6.png/revision/latest?cb=20240727095413", 
                "Controlled", 
                "Overworld", 
                "Player spawn point (can be changed by sleeping in a bed, using a respawn anchor, or with commands).", 
                20, 
                "♥ × 10", 
                1, 
                "♥", 
                1.8, 
                "Height: 1.8 Blocks | Width: 0.6 Blocks", 
                "The player is the main controlled character in Minecraft. The nine default player skins are known as Steve, Alex, Noor, Sunny, Ari, Zuri, Makena, Kai, and Efe with all unchanged skins being split between these nine skins."), 
            new Mob("Polar Bear", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/26/Polar_Bear_attacking.gif/revision/latest?cb=20200302081551", 
                "Neutral | Hostile (adult with a baby)", 
                "Overworld", 
                "Frozen River | Snowy Plains | Ice Spikes | Frozen Ocean | Deep Frozen Ocean | Snowy Slopes | Jagged Peak | Frozen peaks", 
                30, 
                "♥ × 15", 
                6, 
                "♥♥♥", 
                1.4, 
                "Height: 1.4 Blocks | Width: 1.4 Blocks", 
                "Polar bears are neutral mobs that live in icy biomes. Polar bears attack by rearing on their back legs and mauling down with their front paws. Their swimming speed is equal to the player's, making them difficult to get away from if they are attacking in water."), 
            new Mob("Pufferfish", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/78/Pufferfish_large.gif/revision/latest?cb=20190924134001", 
                "Passive", 
                "Overworld", 
                "Lukewarm Ocean | Deep Lukewarm Ocean | Warm Ocean", 
                3, 
                "♥♥", 
                2, 
                "♥ (Poison 7 ♥♥♥♥)", 
                0.96, 
                "Height: 0.96 Blocks | Width: 0.96 Blocks", 
                "Pufferfish are bucketable aquatic mobs found in oceans. Although they never seek out mobs to attack, they will defensively inflate themselves when approached too closely by players, axolotls or non-aquatic mobs, dealing damage and inflicting Poison on them."), 
            new Mob("Rabbit", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/7/77/Rabbit_running.gif/revision/latest?cb=20200428200927", 
                "Passive", 
                "Overworld", 
                "Frozen River | Snowy Beach | Snowy Plains | Ice Spikes | Snowy Slopes | Grove | Snowy Taiga | Old Growth Pine Taiga | Old Growth Spruce Taiga | Taiga | Flower Forest | Meadow | Desert | Frozen Ocean | Cherry Grove", 
                3, 
                "♥♥", 
                0, 
                "♥ × 0", 
                0.402, 
                "Height: 0.402 Blocks | Width: 0.402 Blocks", 
                "A rabbit is an uncommon passive mob and is a source of rabbit's foot, rabbit hide, and raw rabbit. Wild wolves, foxes, and stray cats track down and kill any rabbits."), 
            new Mob("Ravager", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a3/Ravager_JE1.png/revision/latest/scale-to-width-down/1000?cb=20210120025723", 
                "Hostile", 
                "Overworld", 
                "Up to 5 ravagers spawn as part of a raid. Unridden ravagers spawn at waves 3 and 5, a ravager ridden by a pillager spawns at waves 5 and 7, and a ravager ridden by an evoker spawns at wave 7.", 
                100, 
                "♥ × 50", 
                12, 
                "♥ × 6 (Roar 6 ♥♥♥)", 
                2.2, 
                "Height: 2.2 Blocks | Width: 1.95 Blocks", 
                "Ravagers are large hostile mobs that only spawn alongside illagers in raids. They attack players, adult villagers, wandering traders and iron golems by running at them and biting them. They can be briefly stunned by being blocked with a shield, but after recovering they will roar, damaging and knocking away all nearby entities."), 
            new Mob("Salmon", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Salmon.gif/revision/latest?cb=20190923182046", 
                "Passive", 
                "Overworld", 
                "River | Frozen River | Cold Ocean | Deep Cold Ocean | Frozen Ocean | Deep Frozen Ocean", 
                3, 
                "♥♥", 
                0, 
                "♥ × 0", 
                0.75, 
                "Height: 0.75 Blocks | Width: 0.75 Blocks", 
                "Salmon are common bucketable aquatic passive mobs found in oceans and rivers, and a source of raw salmon, and occasionally, bones."), 
            new Mob("Sheep", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1b/Jeb_Sheep_JE2.gif/revision/latest?cb=20201221182841", 
                "Passive", 
                "Overworld", 
                "Grass blocks with at least two block spaces above them.", 
                8, 
                "♥♥♥♥", 
                0, 
                "♥ × 0", 
                1.3, 
                "Height: 1.3 Blocks | Width: 0.9 Blocks", 
                "Sheep are common passive mobs that supply wool and mutton and are found in many of the grassy biomes. Sheep can be attached to a lead."), 
            new Mob("Shulker", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/8c/Shulker_shooting.gif/revision/latest?cb=20200419171116", 
                "Hostile", 
                "The End", 
                "End City", 
                30, 
                "♥ × 15", 
                4, 
                "♥♥", 
                2.0, 
                "Height: 2.0 Blocks | Width: 1 Block", 
                "A shulker is a box-shaped hostile mob found in end cities. It hides in its shell to protect itself and blend in with its surroundings. It attacks by shooting homing bullets at the player which inflict Levitation. It is the only source of shulker shells, which are used to craft shulker boxes."), 
            new Mob("Silverfish", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/22/Silverfish_JE1_BE1.gif/revision/latest?cb=20200125235834", 
                "Hostile", 
                "Overworld", 
                "Broken infested blocks, which generate in strongholds, underground in mountains and windswept hills biomes, in igloo basements and in woodland mansion false portal rooms. Silverfish do not appear if the block is broken with the Silk Touch enchantment. 1-3 silverfish have a 5% chance of spawning from an entity affected by the Infested potion effect when the affected entity is hurt.", 
                8, 
                "♥♥♥♥", 
                1, 
                "♥", 
                0.4, 
                "Height: 0.3 Blocks | Width: 0.4 Blocks", 
                "Silverfish are small hostile mobs that infest stone and deepslate blocks in mountains, strongholds, igloo basements and woodland mansions. They crawl at their targets to bite them, and attacking them will incite other nearby silverfish to emerge from their blocks and attack the aggressor."), 
            new Mob("Skeleton", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/4/47/Skeleton_JE6_BE4.png/revision/latest?cb=20210227130136", 
                "Hostile", 
                "Overworld", 
                "In the Overworld: at a light level of zero. In the Nether: at a light level of seven or less and inside a Nether Fortress or the Soul Sand Valley biome.", 
                20, 
                "♥ × 10", 
                4, 
                "♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "Skeletons are undead common hostile mobs that perform ranged attacks with a bow by shooting arrows."), 
            new Mob("Skeleton Horse", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/de/Skeleton_Horse.png/revision/latest?cb=20190826120115", 
                "Neutral", 
                "Overworld", 
                "A lightning strike during a naturally occurring thunderstorm", 
                15, 
                "♥ × 7.5", 
                0, 
                "♥ × 0", 
                1.6, 
                "Height: 1.6 Blocks | Width: 1.4 Blocks", 
                "A Skeleton Horse is an undead neutral variant of the horse. It sometimes spawns when lightning strikes. The skeleton trap horse is triggered when a player comes within 10 blocks of it, resulting in a second lightning strike. When struck, the skeleton trap horse transforms into a skeleton horseman: a skeleton riding a skeleton horse. It also spawns three additional skeleton horsemen in the vicinity. The skeleton will be equipped with an enchanted iron helmet and an enchanted bow."), 
            new Mob("Slime", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/82/Slime.gif/revision/latest?cb=20220313061726", 
                "Hostile", 
                "Overworld", 
                "Slime chunks below layer 40, regardless of light levels. Swamp biomes between layers 51 and 69 (inclusive) in light levels of 7 or less. Slimes spawn regardless of weather conditions.", 
                20, 
                "♥ × 10", 
                4, 
                "♥♥", 
                2.08, 
                "Height: 2.08 Blocks | Width: 2.08 Blocks", 
                "Slimes are bouncy, cube-shaped hostile mobs that spawn deep underground in particular chunks, or in swamp biomes. They attack by jumping at their targets. They come in three sizes, the larger slimes can split into smaller ones when they die."), 
            new Mob("Sniffer", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ec/Sniffer_sniffsniff.gif/revision/latest?cb=20240729213335", 
                "Passive", 
                "Overworld", 
                "Warm Ocean Ruins", 
                14, 
                "♥ × 7", 
                0, 
                "♥ × 0", 
                1.9, 
                "Height: 1.75 Blocks | Width: 1.9 Blocks", 
                "A sniffer is a passive mob that does not spawn naturally, and can only be hatched from sniffer eggs. It sniffs out and digs out seeds for various unique decorative plants out of dirt, grass, and moss blocks."), 
            new Mob("Snow Golem", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c2/Snow_Golem.png/revision/latest?cb=20190805174855", 
                "Passive", 
                "Overworld", 
                "When created by a player, enderman or dispenser.", 
                4, 
                "♥♥", 
                0, 
                "♥ × 0", 
                1.9, 
                "Height: 1.75 Blocks | Width: 1.9 Blocks", 
                "A snow golem is a buildable passive mob that throws snowballs at monsters, which provokes them into attacking it. Depending on the biome temperature it will also either produce a trail of snow, or take heat damage and die. Thrown snowballs do not deal damage except to blazes and wolves,[6] but the snowballs knock back any mobs that they hit. Additionally, snow golems also attack creepers and never intentionally attack the player. The snow golem's snowballs can set other mobs on fire in addition to knockback, if the shot flies through a lava block or a block that is on fire."), 
            new Mob("Spider", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1f/Spider_JE4_BE3.png/revision/latest/scale-to-width-down/1000?cb=20240729213340", 
                "Neutral (if light level 12 and above) | Hostile (if light level 11 and below and if jockey ridden by skeletons, strays and wither skeletons)", 
                "Overworld", 
                "Light level of 0, 3×1×3 space on solid blocks (spawns only on top of the central block)", 
                16, 
                "♥ × 8", 
                2, 
                "♥♥", 
                1.4, 
                "Height: 0.9 Blocks | Width: 1.4 Blocks", 
                "A spider is a neutral mob that attacks the player in dark areas. Spiders attack by biting the target, and they can also climb walls and lunge at them."), 
            new Mob("Spider Jockey", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/ee/Spider_Jockey.png/revision/latest?cb=20190804090140", 
                "Hostile, Neutral (spider light 12>)", 
                "Overworld", 
                "There is a 1% chance for a spider to spawn with a skeleton riding it, forming a spider jockey.", 
                36, 
                "♥ × 18", 
                4, 
                "♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 1.4 Blocks", 
                "Spider jockeys are the rare appearance of a spider or cave spider being ridden by a skeleton, stray, or wither skeleton."), 
            new Mob("Squid", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ce/Squid.gif/revision/latest?cb=20240729213351", 
                "Passive", 
                "Overworld", 
                "2 to 4 squid can spawn in ocean biomes, and two can spawn in river biomes.", 
                10, 
                "♥♥♥♥♥", 
                0, 
                "♥ × 0", 
                0.95, 
                "Height: 0.95 Blocks | Width: 0.95 Blocks", 
                "A squid is a common passive aquatic mob that spawns in rivers and oceans. When a squid moves, its tentacles open and close, giving it an appearance of pushing itself leisurely forward. A squid hovers in place when first spawned into the world and wanders around aimlessly in three dimensions."), 
            new Mob("Strider", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/a6/Strider_JE2_BE2.gif/revision/latest?cb=20240729214354", 
                "Passive", 
                "The Nether", 
                "Lava sea | Delta | Nether Wastes | Crimson Forest | Warped Forest | Soul Sand Valley | Basalt Deltas", 
                20, 
                "♥ × 10", 
                0, 
                "♥ × 0", 
                1.7, 
                "Height: 1.7 Blocks | Width: 0.9 Blocks", 
                "Striders are passive mobs native to the Nether. They can walk on lava, and be saddled and ridden by the player. A warped fungus on a stick is needed to control a strider, similar to how a pig is controlled by a carrot on a stick."), 
            new Mob("Tadpole", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/11/Tadpole_swimming.gif/revision/latest?cb=20211218125930", 
                "Passive", 
                "Overworld", 
                "From frogspawn", 
                6, 
                "♥♥♥", 
                0, 
                "♥ × 0", 
                0.8, 
                "Height: 0.6 Blocks | Width: 0.8 Blocks", 
                "A tadpole is a bucketable aquatic baby passive mob hatched from frogspawn. They mature into one of the three frog variants depending on the biome in which they mature."), 
            new Mob("Tropical Fish", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ca/Clownfish.png/revision/latest?cb=20240729213357", 
                "Passive", 
                "Overworld", 
                "Mangrove Swamp | Lukewarm Ocean | Deep Lukewarm Ocean | Warm Ocean | Lush Caves", 
                3, 
                "♥♥", 
                0, 
                "♥ × 0", 
                0.52, 
                "Height: 0.52 Blocks | Width: 0.52 Blocks", 
                "Tropical Fish are common bucketable aquatic passive mobs found in oceans, mangrove swamps and lush caves. There are 2,700 naturally occurring variants of tropical fish of different colors and shapes with unique names."), 
            new Mob("Turtle", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e9/Turtle.png/revision/latest?cb=20240729213403", 
                "Passive", 
                "Overworld", 
                "Beach", 
                30, 
                "♥ × 15", 
                0, 
                "♥ × 0", 
                1.2, 
                "Height: 1.2 Blocks | Width: 0.4 Blocks", 
                "A sea turtle is a common passive mob found in beach biomes. They are the only source of scutes, which drop from baby turtles when they mature into adults."), 
            new Mob("Vex", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/84/Vex_JE4.gif/revision/latest?cb=20221123024346", 
                "Hostile", 
                "Overworld", 
                "Summoned by evokers", 
                14, 
                "♥ × 7", 
                9, 
                "♥♥♥♥♥", 
                0.8, 
                "Height: 0.8 Blocks | Width: 0.4 Blocks", 
                "The vex is a small flying hostile mob. It wields an iron sword, can phase through walls, and is only summoned as one of the evoker's attacks. They attack by lunging at their targets with their sword."), 
            new Mob("Villager", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/d/d8/Plains_Villager_Base.png/revision/latest?cb=20250412221255", 
                "Passive", 
                "Overworld", 
                "Village | Igloo basement | When a zombie villager is cured | Upon successful breeding", 
                20, 
                "♥ × 10", 
                0, 
                "♥ × 0", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "Villagers are passive mobs that inhabit villages, work at their professions, breed, and interact with each other. Villagers' outfits vary according to their biome, and adult Villagers' outfits vary depending on their occupation. A player can trade with them using emeralds as currency. They are also the most complex mob in the game, expressing a vast array of behaviors."), 
            new Mob("Vindicator", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c6/Vindicator_attacking.png/revision/latest?cb=20220611075301", 
                "Hostile", 
                "Overworld", 
                "Woodland mansions | Raids Wave 2 and up", 
                24, 
                "♥ × 12", 
                5, 
                "♥♥♥ (Axe ♥ × 6.5)", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A vindicator is an illager equipped with an iron axe. Vindicators appear in woodland mansions and participate in raids. It sprints towards its targets to attack them with its axe."), 
            new Mob("Wandering Trader", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/52/Wandering_Trader.png/revision/latest?cb=20200310000215", 
                "Passive", 
                "Overworld", 
                "Randomly within a 48-block radius of a player | By a claimed bell in a village.", 
                20, 
                "♥ × 10", 
                0, 
                "♥ × 0", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "The wandering trader is a passive mob that randomly spawns near the player. It can trade, making natural items more available, less dangerous to obtain, and in some cases, renewable."), 
            new Mob("Warden", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/86/Warden_sniffing.gif/revision/latest?cb=20220628195720", 
                "Hostile", 
                "Overworld", 
                "When a player activates naturally generated sculk shriekers three times or more.", 
                500, 
                "♥ × 250", 
                30, 
                "♥ × 15 (Sonic Boom ♥ × 5)", 
                2.9, 
                "Height: 2.9 Blocks | Width: 0.9 Blocks", 
                "Warden is an extremely powerful hostile mob summoned by sculk shriekers in the deep dark biome. It attacks by swinging its arms downward, dealing the strongest melee damage of all mobs, and can also release a sonic boom attack that immediately strikes the target, piercing through obstacles and deals damage that cannot be reduced except by the Resistance effect. Wardens are completely blind and rely on vibrations, smell, and touch to detect players and mobs, and can therefore be evaded via sneaking, diversions (snowballs, arrows, etc.) and wool."), 
            new Mob("Witch", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/5/56/Witch_drinking.png/revision/latest?cb=20220611063134", 
                "Hostile", 
                "Overworld", 
                "Light level of 0 | When lightning strikes near a villager | Inside swamp huts | As a part of raids", 
                26, 
                "♥ × 13", 
                6, 
                "♥♥♥ (Poison ♥ × 18)", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "The witch is a hostile mob that uses potions in combat, both in the form of weapons as splash potions and in the form of drinkable potions for defense."), 
            new Mob("Wither", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/3/3b/Wither_JE2_BE2.png/revision/latest?cb=20240729214341", 
                "Hostile", 
                "Overworld", 
                "Built by player", 
                300, 
                "♥ × 150", 
                8, 
                "♥♥♥♥ (Wither ♥ × 5)", 
                3.0, 
                "Height: 3.0 Blocks | Width: 1.0 Blocks", 
                "The wither is a player-constructed and highly destructive undead hostile boss mob that can hover in mid-air and fire barrages of explosive wither skulls at its target (which happens to be everything living). It is the only source of nether stars, which are used to craft beacons."), 
            new Mob("Wither Skeleton", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cd/Wither_Skeleton.png/revision/latest?cb=20191229162539", 
                "Hostile", 
                "The Nether", 
                "Nether Fortress | When a wither reaches half health", 
                20, 
                "♥ × 10", 
                8, 
                "♥♥♥♥ (Wither ♥ × 3)", 
                2.412, 
                "Height: 2.412 Blocks | Width: 0.864 Blocks", 
                "Wither skeletons are tall black variants of skeletons equipped with stone swords that inflict the poison-like Wither effect. They are found exclusively in nether fortresses and are the only source of wither skeleton skulls, as well as the only renewable source of coal."), 
            new Mob("Wolf", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/82/Wolf_shaking.gif/revision/latest?cb=20210212005440", 
                "Neutral", 
                "Overworld", 
                "Grove | Snowy Taiga | Old Growth Pine Taiga | Old Growth Spruce Taiga | Taiga | Forest", 
                20, 
                "♥ × 10", 
                4, 
                "♥♥", 
                0.8, 
                "Height: 0.8 Blocks | Width: 0.6 Blocks", 
                "A wolf is a neutral mob that can be tamed and used to assist in combat with most hostile mobs."), 
            new Mob("Zoglin", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/2/2c/Zoglin_attacking.gif/revision/latest?cb=20220528172426", 
                "Hostile", 
                "Overworld", 
                "When a Hoglin is in the Overworld or the End for 15 seconds", 
                40, 
                "♥ × 20", 
                8, 
                "♥♥♥♥", 
                1.4, 
                "Height: 1.4 Blocks | Width: 1.4 Blocks", 
                "A zoglin is an undead hostile mob created when a hoglin enters the Overworld or End. It never retreats or flees, and attacks players and almost all non-zoglin mobs indiscriminately, using the same tusk attack as its non-zombified counterpart."), 
            new Mob("Zombie", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/8/87/Zombie_JE3_BE2.png/revision/latest?cb=20191227070025", 
                "Hostile", 
                "Overworld", 
                "Light level of 0 | When a husk drowns", 
                20, 
                "♥ × 10", 
                3, 
                "♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "Zombies are common undead hostile mobs that deal melee damage and commonly attack in groups."), 
            new Mob("Zombie Villager", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fd/Plains_Zombie_Villager_Base.png/revision/latest?cb=20211013222051", 
                "Hostile", 
                "Overworld", 
                "Abandoned Village | Light level of 7 or less | When a villager is killed by zombie | Igloo basement", 
                20, 
                "♥ × 10", 
                3, 
                "♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A zombie villager is a variant of the zombie that can be cured into a normal villager using a golden apple while it is under the effect of Weakness."), 
            new Mob("Zombified Piglin", 
                "https://static.wikia.nocookie.net/minecraft_gamepedia/images/1/1c/Zombified_Piglin_BE6.png/revision/latest?cb=20201223164833", 
                "Hostile", 
                "The Nether", 
                "Nether Wastes | Crimson Forest | Nether Fortress | When lightning strikes within 4 blocks of a pig in the Overworld | When a piglin or piglin brute is in the Overworld or in the End for 15 seconds", 
                20, 
                "♥ × 10", 
                8, 
                "♥♥♥♥", 
                1.9, 
                "Height: 1.9 Blocks | Width: 0.6 Blocks", 
                "A zombified piglin (formerly named Zombie Pigman) is a neutral undead variant of the piglin that inhabits the Nether. Zombified piglins normally ignore players, but if one is attacked, it and all zombified piglins in the vicinity become enraged and attack the aggressor with their golden swords.")
        );
    }
}